name: linting, testing, building
run-name: ${{ github.actor }} UR
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18.16.0'
      - name: install modules
        run: yarn
      - name: build production project
        run: yarn build:prod
        if: always()
      - name: linting css files
        run: yarn lint:scss
        if: always()
      - name: unit testing
        run: yarn test:unit
        if: always()
      - name: build storybook
        run: yarn storybook:build
        if: always()
      - name: screenshot testing
        run: yarn test:ui:ci
        if: always()
